src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $firstname = null;

    #[ORM\Column(length: 255)]
    private ?string $lastname = null;

    #[ORM\Column(length: 255)]
    private ?string $nickname = null;

    #[ORM\Column(length: 128, unique: true)]
    #[Gedmo\Slug(fields: ['nickname'])]
    private $slug;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(type: Types::DATE_IMMUTABLE)]
    #[Gedmo\Timestampable(on: 'create')]
    private ?\DateTimeInterface $registrationDate = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Trick::class)]
    private Collection $tricks;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Comment::class)]
    private Collection $comments;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: PhotoTrick::class)]
    private Collection $photoTricks;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: VideoTrick::class)]
    private Collection $videoTricks;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $avatar = null;

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;

    public function __construct()
    {

        $this->setRegistrationDate(new \DateTimeImmutable(' now'));
        $this->tricks = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->photoTricks = new ArrayCollection();
        $this->videoTricks = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getNickname(): ?string
    {
        return $this->nickname;
    }

    public function setNickname(string $nickname): self
    {
        $this->nickname = $nickname;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getRegistrationDate(): ?\DateTimeInterface
    {
        return $this->registrationDate;
    }

    public function setRegistrationDate(\DateTimeInterface $registrationDate): self
    {
        $this->registrationDate = $registrationDate;

        return $this;
    }

    /**
     * @return Collection<int, Trick>
     */
    public function getTricks(): Collection
    {
        return $this->tricks;
    }

    public function addTrick(Trick $trick): self
    {
        if (!$this->tricks->contains($trick)) {
            $this->tricks->add($trick);
            $trick->setUser($this);
        }

        return $this;
    }

    public function removeTrick(Trick $trick): self
    {
        if ($this->tricks->removeElement($trick)) {
            // set the owning side to null (unless already changed)
            if ($trick->getUser() === $this) {
                $trick->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setUser($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getUser() === $this) {
                $comment->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, PhotoTrick>
     */
    public function getPhotoTricks(): Collection
    {
        return $this->photoTricks;
    }

    public function addPhotoTrick(PhotoTrick $photoTrick): self
    {
        if (!$this->photoTricks->contains($photoTrick)) {
            $this->photoTricks->add($photoTrick);
            $photoTrick->setUser($this);
        }

        return $this;
    }

    public function removePhotoTrick(PhotoTrick $photoTrick): self
    {
        if ($this->photoTricks->removeElement($photoTrick)) {
            // set the owning side to null (unless already changed)
            if ($photoTrick->getUser() === $this) {
                $photoTrick->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, VideoTrick>
     */
    public function getVideoTricks(): Collection
    {
        return $this->videoTricks;
    }

    public function addVideoTrick(VideoTrick $videoTrick): self
    {
        if (!$this->videoTricks->contains($videoTrick)) {
            $this->videoTricks->add($videoTrick);
            $videoTrick->setUser($this);
        }

        return $this;
    }

    public function removeVideoTrick(VideoTrick $videoTrick): self
    {
        if ($this->videoTricks->removeElement($videoTrick)) {
            // set the owning side to null (unless already changed)
            if ($videoTrick->getUser() === $this) {
                $videoTrick->setUser(null);
            }
        }

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(?string $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function __toString(): string
    {
        return $this->getNickname() ;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }
    public function getSlug()
    {
        return $this->slug;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use http\Env\Url;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('email',EmailType::class)
            //->add('roles')
            ->add('password',PasswordType::class)
            ->add('firstname')
            ->add('lastname')
            ->add('nickname')
            ->add('description',TextareaType::class)
            ->add('avatar', FileType::class, [
                'required' => false,
                'mapped' => false,
                'data_class' => null,
                'attr' => ['accept' => 'image/*']
            ])
            ->add('removeAvatar', CheckboxType::class, [
                'required' => false,
                'mapped' => false
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use App\Repository\TrickRepository;
use App\Repository\UserRepository;
use App\Service\FileUploader;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/user')]
class UserController extends AbstractController
{
    /*#[Route('/', name: 'app_user_index', methods: ['GET'])]
    public function index(UserRepository $userRepository): Response
    {
        return $this->render('user/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }*/
 /*   #[Route('/trick', name: 'app_user_trick_index', methods: ['GET'])]
    public function TrickController(TrickRepository $trickRepository ): Response
    {
        return $this->render('user/trick/index.html.twig', [
            'tricks' => $trickRepository->findAll(),
        ]);
    }*/




  /*  #[Route('/new', name: 'app_user_new', methods: ['GET', 'POST'])]
    public function new(Request $request, UserRepository $userRepository, FileUploader $fileUploader): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $userRepository->save($user, true);

            $this->addFlash('success', 'Félicitation'.$user->getNickname() .'Votre compte a bien été créé !');
            return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('user/new.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }*/

    #[Route('/{slug}', name: 'app_user_show', methods: ['GET'])]
    public function show(User $user ): Response
    {
        return $this->render('user/show.html.twig', [
            'user' => $user,

        ]);
    }


    #[Route('/{slug}/edit', name: 'app_user_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, User $user, UserRepository $userRepository, FileUploader $fileUploader): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $avatar = $form->get('avatar')->getData();
            if($avatar){
                $fileName = $fileUploader->upload($avatar);
                $user->setAvatar($fileName);
            }else if ($form->get('removeAvatar')->getData()){
                unlink($this->getParameter('uploads_path').'/'.$user->getAvatar());
                $user->setAvatar(null);
            }



            $userRepository->save($user, true);

            return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('user/edit.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    #[Route('/{slug}', name: 'app_user_delete', methods: ['POST'])]
    public function delete(Request $request, User $user, UserRepository $userRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $userRepository->remove($user, true);
        }

        return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
    }



}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('app_user_delete', {'slug': user.slug}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn">Delete</button>
</form>

templates/user/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit user{% endblock %}

{% block body %}
    <h1>Modifié les paramètres utilisateurs</h1>
    {{ form_start(form) }}
    {{ form_row(form.avatar) }}
    <img src="{{ asset(uploads_dir ~ user.avatar) }}" class="img-thumbnail" alt="Avatar de {{ user.nickname }}">
    {{ form_row(form.removeAvatar) }}
    <button class="btn" type="submit">Modifier</button>
    {{ form_end(form) }}

{# {{ include('user/_form.html.twig', {'button_label': 'Update'}) }} #}
    <p>Trick créé :</p>

    {% for trick in user.tricks  %}

        <li> {{ trick.nameTrick }} dans le groupe {{ trick.groupTrick.name }}</li>
    {% endfor %}



    <p>Commentaire crée :</p>
    {% for comment in user.comments %}
        <li>{{ comment.comment }}</li>

    {% endfor %}


    {{ include('user/_delete_form.html.twig') }}
{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}user index{% endblock %}

{% block body %}
    <h1>user index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>User vérifier</th>
                <th>Email</th>
                <th>Roles</th>
                <th>Password</th>
                <th>Firstname</th>
                <th>Lastname</th>
                <th>Nickname</th>
                <th>Description</th>
                <th>RegistrationDate</th>
                <th>Avatar</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                {% if user.verified %}
                    <td>Vérifier !</td>
                {% else %}
                    <td>Non vérifier !</td>
                {% endif %}
                <td>{{ user.email }}</td>
                <td>{{ user.roles ? user.roles|json_encode : '' }}</td>
                <td>{{ user.password }}</td>
                <td>{{ user.firstname }}</td>
                <td>{{ user.lastname }}</td>
                <td>{{ user.nickname }}</td>
                <td>{{ user.description }}</td>
                <td>{{ user.registrationDate ? user.registrationDate|date('Y-m-d') : '' }}</td>
                <td><img src="{{ asset(uploads_dir ~ user.avatar ) }}" alt="Photo principal"></td>

                <td>
                    <a href="{{ path('app_user_show', {'slug': user.slug}) }}">show</a>
                    <a href="{{ path('app_user_edit', {'slug': user.slug}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="11">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_user_new') }}">Create new</a>
{% endblock %}

templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New user{% endblock %}

{% block body %}
    <h1>Create new user</h1>

    {{ include('user/_form.html.twig') }}

    <a href="{{ path('app_user_index') }}">back to list</a>
{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}


{% block title %}profil de {{ app.user.nickname }}{% endblock %}

{% block body %}
<div class="container" >
    <h1 class="content">Hey {{ app.user.nickname }} Voilà ton espace rien qu'à toi !</h1>

    <table class="table">
        <tbody>

            <tr>
                <th class="content">Email</th>
                <td>{{ user.email }}</td>
            </tr>

            <tr>
                <th class="content">Firstname</th>
                <td>{{ user.firstname }}</td>
            </tr>
            <tr>
                <th class="content">Lastname</th>
                <td>{{ user.lastname }}</td>
            </tr>
            <tr>
                <th class="content" >Nickname</th>
                <td>{{ user.nickname }}</td>
            </tr>
            <tr>
                <th class="content">Description</th>
                <td>{{ user.description }}</td>
            </tr>
            <tr>
                <th class="content">RegistrationDate</th>
                <td>{{ user.registrationDate ? user.registrationDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th class="content">Avatar</th>
                <td><img class="user_avatar" src="{{ asset(uploads_dir ~ user.avatar ) }}" alt="Photo principal"></td>
            </tr>
        </tbody>
    </table>



    <a class="btn" href="{{ path('app_user_edit', {'slug': user.slug}) }}">Modifier son profil</a>
</div>
{% endblock %}